services:
  portfel_app:
    container_name: portfel_app
    build: .
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - portfel_db
    networks:
      - app_network

  portfel_db:
    container_name: portfel_db
    image: postgres:16.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
