CREATE TABLE IF NOT EXISTS account (
    id VARCHAR PRIMARY KEY,
    number INTEGER NOT NULL,
    balance NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS logs (
    id VARCHAR PRIMARY KEY,
    error BOOLEAN NOT NULL,
    context JSONB NOT NULL,
    message TEXT NOT NULL,
    date TIMESTAMP
);
